// CoreML convolution capacity benchmark.
//
// Companion to measure_conv_universal.m, which measures the same workload
// (L chained 3x3 convolutions over [B, Ci, H, W], NCHW, SAME padding) through
// MPSGraph. This binary drives the model via CoreML instead, so the two paths
// can be compared on identical arithmetic. Models are authored in MIL and
// generated by tools/gen_conv_mil.py.
//
// Unlike MPSGraph, which needs the private preferredDevice property and gives no
// confirmation of where the work landed, CoreML exposes MLComputePlan: --plan
// reports the preferred compute device for every operation in the program.

#import <locale.h>
#import <time.h>

#import <CoreML/CoreML.h>
#import <Foundation/Foundation.h>

typedef struct {
  NSUInteger B, H, W, Ci, Co, K, L;
  NSUInteger iterations;
  NSUInteger warmup;
  NSString *modelPath;
  MLComputeUnits units;
  NSString *unitsName;
  BOOL showPlan;
  BOOL checkOutput;
  BOOL verbose;
  BOOL denseInput;
} BenchConfig;

// Fill buffer with the tiled non-zero pattern used by measure_conv_universal.m,
// so CoreML and MPSGraph runs see bit-for-bit the same input.
static void fillRepeatFloat16(void *buffer, size_t byteCount) {
  if (!buffer || byteCount == 0) return;
  uint16_t *p = (uint16_t *)buffer;
  size_t count = byteCount / sizeof(uint16_t);
  static const uint16_t fp16_pattern[4] = {0x2C00, 0xAC00, 0x2800, 0xA800};
  for (size_t i = 0; i < count; i++) {
    p[i] = fp16_pattern[i % 4];
  }
}

// Random-sign +/-0.0625 (fp16 0x2C00 / 0xAC00). The tiled pattern above is
// structured enough to cancel exactly under the convolution reduction, which
// hands every layer after the first an all-zero tensor -- precisely what H17+
// zero-skipping detects. Random signs keep the reduction non-degenerate.
// Deterministic (fixed-seed xorshift64) so runs are reproducible.
static void fillDenseFloat16(void *buffer, size_t byteCount) {
  if (!buffer || byteCount == 0) return;
  uint16_t *p = (uint16_t *)buffer;
  size_t count = byteCount / sizeof(uint16_t);
  uint64_t state = 0x9E3779B97F4A7C15ULL;
  for (size_t i = 0; i < count; i++) {
    state ^= state << 13;
    state ^= state >> 7;
    state ^= state << 17;
    // Sign bit only: magnitude stays constant at 0.0625.
    p[i] = (state & 1) ? 0xAC00 : 0x2C00;
  }
}

static double nowSeconds(void) {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return ts.tv_sec + ts.tv_nsec / 1e9;
}

static NSString *deviceLabel(id<MLComputeDeviceProtocol> device) {
  if (!device) return @"unknown";
  if ([device isKindOfClass:[MLNeuralEngineComputeDevice class]]) return @"ANE";
  if ([device isKindOfClass:[MLGPUComputeDevice class]]) return @"GPU";
  if ([device isKindOfClass:[MLCPUComputeDevice class]]) return @"CPU";
  return NSStringFromClass([device class]);
}

// Compile a .mlpackage to .mlmodelc. Already-compiled inputs pass through.
static NSURL *compileModel(NSString *path, double *compileMs, NSError **error) {
  NSURL *url = [NSURL fileURLWithPath:path];
  if ([path hasSuffix:@".mlmodelc"]) {
    *compileMs = 0.0;
    return url;
  }

  double start = nowSeconds();
  dispatch_semaphore_t sem = dispatch_semaphore_create(0);
  __block NSURL *compiled = nil;
  __block NSError *compileError = nil;
  [MLModel compileModelAtURL:url
           completionHandler:^(NSURL *compiledModelURL, NSError *err) {
             // The compiled model lives in a temporary location that is torn
             // down once this handler returns, so copy it somewhere stable.
             if (compiledModelURL) {
               NSString *dest = [NSTemporaryDirectory()
                   stringByAppendingPathComponent:
                       [NSString stringWithFormat:@"measure_conv_coreml_%@",
                                                  compiledModelURL.lastPathComponent]];
               NSURL *destURL = [NSURL fileURLWithPath:dest];
               NSFileManager *fm = [NSFileManager defaultManager];
               [fm removeItemAtURL:destURL error:nil];
               NSError *copyError = nil;
               if ([fm copyItemAtURL:compiledModelURL toURL:destURL error:&copyError]) {
                 compiled = destURL;
               } else {
                 compileError = copyError;
               }
             } else {
               compileError = err;
             }
             dispatch_semaphore_signal(sem);
           }];
  dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);
  *compileMs = (nowSeconds() - start) * 1000.0;

  if (!compiled && error) *error = compileError;
  return compiled;
}

// The generator names tensors from the MIL graph (input "x", output "conv_<L-1>"),
// so read the names off the model rather than hardcoding them.
static NSString *soleInputName(MLModel *model) {
  return model.modelDescription.inputDescriptionsByName.allKeys.firstObject;
}

static NSString *soleOutputName(MLModel *model) {
  return model.modelDescription.outputDescriptionsByName.allKeys.firstObject;
}

// A dimension mismatch between the model and the --size/--channels/--layers
// flags would yield a plausible-looking but wrong TOPS figure, so refuse to run.
static BOOL validateShape(MLModel *model, BenchConfig cfg) {
  MLFeatureDescription *desc =
      model.modelDescription.inputDescriptionsByName[soleInputName(model)];
  NSArray<NSNumber *> *shape = desc.multiArrayConstraint.shape;
  NSArray<NSNumber *> *expected = @[ @(cfg.B), @(cfg.Ci), @(cfg.H), @(cfg.W) ];
  if (![shape isEqualToArray:expected]) {
    // NSArray's own description is multi-line; keep this on one readable line.
    NSString *got = [shape componentsJoinedByString:@", "];
    NSString *want = [expected componentsJoinedByString:@", "];
    fprintf(stderr,
            "error: model input shape [%s] does not match requested dimensions [%s].\n"
            "       Regenerate with: python3 tools/gen_conv_mil.py --batch %lu "
            "--size %lu --channels %lu --layers %lu\n",
            got.UTF8String, want.UTF8String,
            (unsigned long)cfg.B, (unsigned long)cfg.H, (unsigned long)cfg.Ci,
            (unsigned long)cfg.L);
    return NO;
  }
  if (desc.multiArrayConstraint.dataType != MLMultiArrayDataTypeFloat16) {
    fprintf(stderr,
            "error: model input is not Float16; an FP32 boundary would add a "
            "per-prediction CPU cast and invalidate the measurement.\n");
    return NO;
  }
  return YES;
}

// Report the preferred compute device per operation. This is what MPSGraph
// cannot tell us: proof the convolutions actually ran on the ANE.
// Takes the compiled .mlmodelc URL: handed a .mlpackage, MLComputePlan throws an
// uncatchable C++ ios_base::failure rather than returning an error.
static void dumpComputePlan(NSURL *compiledURL, MLModelConfiguration *config,
                            BenchConfig cfg) {
  if (![MLComputePlan respondsToSelector:@selector(loadContentsOfURL:
                                                        configuration:
                                                    completionHandler:)]) {
    printf("   Compute plan unavailable on this OS version (needs macOS 14.4+).\n");
    return;
  }

  dispatch_semaphore_t sem = dispatch_semaphore_create(0);
  __block MLComputePlan *plan = nil;
  __block NSError *planError = nil;
  [MLComputePlan loadContentsOfURL:compiledURL
                    configuration:config
                completionHandler:^(MLComputePlan *loaded, NSError *err) {
                  plan = loaded;
                  planError = err;
                  dispatch_semaphore_signal(sem);
                }];
  dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);

  if (!plan) {
    printf("   Failed to load compute plan: %s\n",
           planError.localizedDescription.UTF8String);
    return;
  }

  MLModelStructureProgram *program = plan.modelStructure.program;
  if (!program) {
    printf("   Model structure is not an ML program; cannot walk operations.\n");
    return;
  }

  printf("\n--- Compute Plan (%s) ---\n", cfg.unitsName.UTF8String);
  NSUInteger convTotal = 0, convOnANE = 0;
  NSMutableDictionary<NSString *, NSNumber *> *byDevice = [NSMutableDictionary new];

  for (NSString *fnName in program.functions) {
    MLModelStructureProgramFunction *fn = program.functions[fnName];
    for (MLModelStructureProgramOperation *op in fn.block.operations) {
      // const ops carry no compute and would drown out the real work.
      // Names may be opset-qualified ("ios18.const") or bare.
      if ([op.operatorName hasSuffix:@"const"]) continue;

      MLComputePlanDeviceUsage *usage = [plan computeDeviceUsageForMLProgramOperation:op];
      NSString *label = deviceLabel(usage.preferredComputeDevice);
      MLComputePlanCost *cost = [plan estimatedCostOfMLProgramOperation:op];

      byDevice[label] = @(byDevice[label].unsignedIntegerValue + 1);
      // Compiled programs report opset-qualified names, e.g. "ios18.conv".
      if ([op.operatorName hasSuffix:@"conv"]) {
        convTotal++;
        if ([label isEqualToString:@"ANE"]) convOnANE++;
      }

      if (cfg.verbose) {
        NSString *outName = op.outputs.firstObject.name ?: @"?";
        printf("   %-24s %-12s -> %-4s (cost weight %.4f)\n",
               outName.UTF8String, op.operatorName.UTF8String, label.UTF8String,
               cost ? cost.weight : 0.0);
      }
    }
  }

  for (NSString *label in [byDevice.allKeys sortedArrayUsingSelector:@selector(compare:)]) {
    printf("   ops on %-4s: %lu\n", label.UTF8String,
           (unsigned long)byDevice[label].unsignedIntegerValue);
  }
  printf("   conv ops on ANE: %lu/%lu%s\n", (unsigned long)convOnANE,
         (unsigned long)convTotal,
         (convTotal > 0 && convOnANE == convTotal) ? "" : "  <-- not fully on ANE");
  printf("\n");
}

static void printUsage(const char *argv0) {
  printf("Usage: %s [options]\n\n", argv0);
  printf("CoreML convolution capacity benchmark (MIL-authored models).\n");
  printf("Generate models first with: make models\n\n");
  printf("Options:\n");
  printf("  --model <path>     .mlpackage or .mlmodelc to benchmark "
         "(default: models/conv_fp16.mlpackage)\n");
  printf("  --units <target>   ane | gpu | cpu | all (default: ane)\n");
  printf("  --batch <B>        batch dimension (default: 1)\n");
  printf("  --size <H>         spatial height and width (default: 256)\n");
  printf("  --channels <C>     input and output channels (default: 128)\n");
  printf("  --kernel <K>       kernel size (default: 3)\n");
  printf("  --layers <L>       number of chained conv layers (default: 20)\n");
  printf("  --input <mode>     dense (random-sign, non-cancelling) | repeat "
         "(tiled pattern matching the MPSGraph binaries) (default: dense)\n");
  printf("  --iterations <N>   timed prediction count (default: 20)\n");
  printf("  --warmup <N>       warmup prediction count (default: 3)\n");
  printf("  --plan             dump per-operation compute device placement\n");
  printf("  --check            print output samples to verify finite, non-zero results\n");
  printf("  --verbose          per-operation detail in the compute plan\n");
  printf("  --help             this message\n");
}

static BOOL runBenchmark(BenchConfig cfg) {
  @autoreleasepool {
    NSFileManager *fm = [NSFileManager defaultManager];
    if (![fm fileExistsAtPath:cfg.modelPath]) {
      fprintf(stderr,
              "error: model not found at %s\n"
              "       Run 'make models' (or python3 tools/gen_conv_mil.py) first.\n",
              cfg.modelPath.UTF8String);
      return NO;
    }

    double compileMs = 0.0;
    NSError *error = nil;
    NSURL *compiledURL = compileModel(cfg.modelPath, &compileMs, &error);
    if (!compiledURL) {
      fprintf(stderr, "error: failed to compile model: %s\n",
              error.localizedDescription.UTF8String);
      return NO;
    }

    MLModelConfiguration *config = [MLModelConfiguration new];
    config.computeUnits = cfg.units;
    // Guarded so this source still builds and runs against older SDKs/OSes,
    // matching how the MPSGraph benchmarks probe for private API.
    if ([config respondsToSelector:@selector(optimizationHints)]) {
      MLOptimizationHints *hints = [MLOptimizationHints new];
      if ([hints respondsToSelector:@selector(setReshapeFrequency:)]) {
        hints.reshapeFrequency = MLReshapeFrequencyHintInfrequent;
      }
      if ([hints respondsToSelector:@selector(setSpecializationStrategy:)]) {
        hints.specializationStrategy = MLSpecializationStrategyFastPrediction;
      }
      config.optimizationHints = hints;
    }

    // Model load is where the ANE program is compiled and cached by the OS, so
    // it is timed separately from inference.
    double loadStart = nowSeconds();
    MLModel *model = [MLModel modelWithContentsOfURL:compiledURL
                                      configuration:config
                                              error:&error];
    double loadMs = (nowSeconds() - loadStart) * 1000.0;
    if (!model) {
      fprintf(stderr, "error: failed to load model: %s\n",
              error.localizedDescription.UTF8String);
      return NO;
    }

    if (!validateShape(model, cfg)) return NO;

    NSString *inputName = soleInputName(model);
    NSString *outputName = soleOutputName(model);

    if (cfg.showPlan) dumpComputePlan(compiledURL, config, cfg);

    NSArray<NSNumber *> *shape = @[ @(cfg.B), @(cfg.Ci), @(cfg.H), @(cfg.W) ];
    MLMultiArray *input = [[MLMultiArray alloc] initWithShape:shape
                                                    dataType:MLMultiArrayDataTypeFloat16
                                                       error:&error];
    if (!input) {
      fprintf(stderr, "error: failed to allocate input: %s\n",
              error.localizedDescription.UTF8String);
      return NO;
    }
    BOOL dense = cfg.denseInput;
    [input getMutableBytesWithHandler:^(void *bytes, NSInteger size,
                                        NSArray<NSNumber *> *strides) {
      if (dense) {
        fillDenseFloat16(bytes, (size_t)size);
      } else {
        fillRepeatFloat16(bytes, (size_t)size);
      }
    }];

    MLDictionaryFeatureProvider *features =
        [[MLDictionaryFeatureProvider alloc] initWithDictionary:@{inputName : input}
                                                         error:&error];
    if (!features) {
      fprintf(stderr, "error: failed to build feature provider: %s\n",
              error.localizedDescription.UTF8String);
      return NO;
    }

    // Reuse one output buffer across predictions; otherwise every call allocates
    // a fresh multi-megabyte MLMultiArray and we end up timing malloc.
    MLPredictionOptions *options = [MLPredictionOptions new];
    MLMultiArray *outputBacking = nil;
    if ([options respondsToSelector:@selector(setOutputBackings:)]) {
      MLMultiArrayConstraint *outConstraint =
          model.modelDescription.outputDescriptionsByName[outputName].multiArrayConstraint;
      outputBacking = [[MLMultiArray alloc] initWithShape:outConstraint.shape
                                                dataType:outConstraint.dataType
                                                   error:&error];
      if (outputBacking) {
        options.outputBackings = @{outputName : outputBacking};
      }
    }

    for (NSUInteger i = 0; i < cfg.warmup; i++) {
      if (![model predictionFromFeatures:features options:options error:&error]) {
        fprintf(stderr, "error: warmup prediction failed: %s\n",
                error.localizedDescription.UTF8String);
        return NO;
      }
    }

    id<MLFeatureProvider> result = nil;
    double start = nowSeconds();
    for (NSUInteger i = 0; i < cfg.iterations; i++) {
      result = [model predictionFromFeatures:features options:options error:&error];
      if (!result) {
        fprintf(stderr, "error: prediction failed: %s\n",
                error.localizedDescription.UTF8String);
        return NO;
      }
    }
    double duration = nowSeconds() - start;

    double avg = duration / cfg.iterations;
    double totalOps =
        2.0 * cfg.B * cfg.H * cfg.W * cfg.Ci * cfg.Co * cfg.K * cfg.K * cfg.L;
    double tops = (totalOps / 1e12) / avg;

    printf("[CoreML %s FP16] Compile: %.2f ms, Load: %.2f ms, Avg: %.2f ms, "
           "Speed: %.4f TOPS (%.1f FPS)\n",
           cfg.unitsName.UTF8String, compileMs, loadMs, avg * 1000.0, tops,
           1.0 / avg);

    if (cfg.checkOutput) {
      MLMultiArray *out = [result featureValueForName:outputName].multiArrayValue;
      if (!out) {
        printf("   Output check: no multi-array output named %s\n",
               outputName.UTF8String);
      } else {
        __block double minAbs = INFINITY, maxAbs = 0.0;
        __block NSUInteger nonFinite = 0, zeros = 0, total = 0;
        __block NSMutableArray<NSString *> *samples = [NSMutableArray array];
        [out getBytesWithHandler:^(const void *bytes, NSInteger size) {
          const _Float16 *p = (const _Float16 *)bytes;
          total = (NSUInteger)(size / sizeof(_Float16));
          for (NSUInteger i = 0; i < total; i++) {
            double v = (double)p[i];
            if (!isfinite(v)) {
              nonFinite++;
              continue;
            }
            if (v == 0.0) zeros++;
            double a = fabs(v);
            if (a < minAbs && a > 0.0) minAbs = a;
            if (a > maxAbs) maxAbs = a;
            if (i < 6) [samples addObject:[NSString stringWithFormat:@"%g", v]];
          }
        }];
        printf("   Output check: %lu elements, first: [%s]\n", (unsigned long)total,
               [samples componentsJoinedByString:@", "].UTF8String);
        printf("   Output check: |v| range [%g, %g], zeros: %lu, non-finite: %lu%s\n",
               isfinite(minAbs) ? minAbs : 0.0, maxAbs, (unsigned long)zeros,
               (unsigned long)nonFinite,
               nonFinite > 0 ? "  <-- NaN/Inf across the conv chain" : "");
      }
    }

    return YES;
  }
}

int main(int argc, char *argv[]) {
  setlocale(LC_NUMERIC, "");

  BenchConfig cfg = {
      .B = 1,
      .H = 256,
      .W = 256,
      .Ci = 128,
      .Co = 128,
      .K = 3,
      .L = 20,
      .iterations = 20,
      .warmup = 3,
      .modelPath = @"models/conv_fp16.mlpackage",
      .units = MLComputeUnitsCPUAndNeuralEngine,
      .unitsName = @"ANE",
      .showPlan = NO,
      .checkOutput = NO,
      .verbose = NO,
      .denseInput = YES,
  };

  for (int i = 1; i < argc; i++) {
    NSString *arg = [NSString stringWithUTF8String:argv[i]];
    if ([arg isEqualToString:@"--model"] && i + 1 < argc) {
      cfg.modelPath = [NSString stringWithUTF8String:argv[++i]];
    } else if ([arg isEqualToString:@"--units"] && i + 1 < argc) {
      NSString *u = [[NSString stringWithUTF8String:argv[++i]] lowercaseString];
      if ([u isEqualToString:@"ane"]) {
        cfg.units = MLComputeUnitsCPUAndNeuralEngine;
        cfg.unitsName = @"ANE";
      } else if ([u isEqualToString:@"gpu"]) {
        cfg.units = MLComputeUnitsCPUAndGPU;
        cfg.unitsName = @"GPU";
      } else if ([u isEqualToString:@"cpu"]) {
        cfg.units = MLComputeUnitsCPUOnly;
        cfg.unitsName = @"CPU";
      } else if ([u isEqualToString:@"all"]) {
        cfg.units = MLComputeUnitsAll;
        cfg.unitsName = @"All";
      } else {
        fprintf(stderr, "error: unknown --units value '%s'\n", u.UTF8String);
        return 1;
      }
    } else if ([arg isEqualToString:@"--batch"] && i + 1 < argc) {
      cfg.B = atoi(argv[++i]);
    } else if ([arg isEqualToString:@"--size"] && i + 1 < argc) {
      cfg.H = cfg.W = atoi(argv[++i]);
    } else if ([arg isEqualToString:@"--channels"] && i + 1 < argc) {
      cfg.Ci = cfg.Co = atoi(argv[++i]);
    } else if ([arg isEqualToString:@"--kernel"] && i + 1 < argc) {
      cfg.K = atoi(argv[++i]);
    } else if ([arg isEqualToString:@"--layers"] && i + 1 < argc) {
      cfg.L = atoi(argv[++i]);
    } else if ([arg isEqualToString:@"--iterations"] && i + 1 < argc) {
      cfg.iterations = atoi(argv[++i]);
    } else if ([arg isEqualToString:@"--warmup"] && i + 1 < argc) {
      cfg.warmup = atoi(argv[++i]);
    } else if ([arg isEqualToString:@"--input"] && i + 1 < argc) {
      NSString *v = [[NSString stringWithUTF8String:argv[++i]] lowercaseString];
      if ([v isEqualToString:@"dense"]) {
        cfg.denseInput = YES;
      } else if ([v isEqualToString:@"repeat"]) {
        cfg.denseInput = NO;
      } else {
        fprintf(stderr, "error: unknown --input value '%s'\n", v.UTF8String);
        return 1;
      }
    } else if ([arg isEqualToString:@"--plan"]) {
      cfg.showPlan = YES;
    } else if ([arg isEqualToString:@"--check"]) {
      cfg.checkOutput = YES;
    } else if ([arg isEqualToString:@"--verbose"]) {
      cfg.verbose = YES;
    } else if ([arg isEqualToString:@"--help"] || [arg isEqualToString:@"-h"]) {
      printUsage(argv[0]);
      return 0;
    } else {
      fprintf(stderr, "error: unknown argument '%s'\n", arg.UTF8String);
      printUsage(argv[0]);
      return 1;
    }
  }

  if (cfg.iterations == 0) {
    fprintf(stderr, "error: --iterations must be at least 1\n");
    return 1;
  }

  printf("CoreML Conv2D Capacity Benchmark\n");
  printf("Model: %s\n", cfg.modelPath.UTF8String);
  printf("Input: %s\n", cfg.denseInput ? "dense (random-sign)" : "repeat (tiled)");
  printf("Workload: [%lu, %lu, %lu, %lu] x %lu conv%lux%lu (Co=%lu), "
         "%.2f GOPs/pass, %lu iterations\n",
         (unsigned long)cfg.B, (unsigned long)cfg.Ci, (unsigned long)cfg.H,
         (unsigned long)cfg.W, (unsigned long)cfg.L, (unsigned long)cfg.K,
         (unsigned long)cfg.K, (unsigned long)cfg.Co,
         2.0 * cfg.B * cfg.H * cfg.W * cfg.Ci * cfg.Co * cfg.K * cfg.K * cfg.L / 1e9,
         (unsigned long)cfg.iterations);

  return runBenchmark(cfg) ? 0 : 1;
}
